{
 "title": "Ambient Weather",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Outdoor Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambient_weather_outdoor_temperature_celsius",
     "legendFormat": "Outdoor Temp"
    }
   ]
  },
  {
   "title": "Outdoor Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ambient_weather_outdoor_humidity_percent",
     "legendFormat": "Outdoor Humidity"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ambient_weather_wind_speed_mph", "legendFormat": "Wind Speed" }
   ]
  },
  {
   "title": "Wind Rose",
   "type": "spectraphilic-windrose-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "ambient_weather_wind_gust_mph", "legendFormat": "speed" },
    {
     "expr": "ambient_weather_wind_direction_degrees",
     "legendFormat": "direction"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ambient_weather_outdoor_temperature_celsius",
     "legendFormat": "Outdoor"
    },
    {
     "expr": "ambient_weather_indoor_temperature_celsius",
     "legendFormat": "Indoor"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ambient_weather_outdoor_humidity_percent",
     "legendFormat": "Outdoor"
    },
    {
     "expr": "ambient_weather_indoor_humidity_percent",
     "legendFormat": "Indoor"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    { "expr": "ambient_weather_wind_speed_mph", "legendFormat": "Wind Speed" },
    { "expr": "ambient_weather_wind_gust_mph", "legendFormat": "Wind Gust" },
    {
     "expr": "ambient_weather_max_daily_gust_mph",
     "legendFormat": "Max Daily Gust"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "expr": "ambient_weather_rain_hourly_inches",
     "legendFormat": "Hourly"
    },
    {
     "expr": "ambient_weather_rain_daily_inches",
     "legendFormat": "Daily"
    },
    {
     "expr": "ambient_weather_rain_weekly_inches",
     "legendFormat": "Weekly"
    },
    {
     "expr": "ambient_weather_rain_monthly_inches",
     "legendFormat": "Monthly"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "expr": "ambient_weather_barometric_pressure_relative_inhg",
     "legendFormat": "Relative (Sea Level)"
    },
    {
     "expr": "ambient_weather_barometric_pressure_absolute_inhg",
     "legendFormat": "Absolute (Station)"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt/m2" } },
   "targets": [
    {
     "expr": "ambient_weather_solar_radiation_wm2",
     "legendFormat": "Solar Radiation"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "gm3" } },
   "targets": [
    {
     "expr": "ambient_weather_absolute_humidity_gm3",
     "legendFormat": "Absolute Humidity"
    }
   ]
  },
  {
   "title": "Temperature Indices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ambient_weather_dew_point_celsius",
     "legendFormat": "Dew Point"
    },
    {
     "expr": "ambient_weather_heat_index_celsius",
     "legendFormat": "Heat Index"
    },
    {
     "expr": "ambient_weather_wind_chill_celsius",
     "legendFormat": "Wind Chill"
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "targets": [
    {
     "expr": "ambient_weather_atmospheric_pressure_hpa",
     "legendFormat": "Atmospheric Pressure"
    }
   ]
  },
  {
   "title": "Vapor Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "targets": [
    {
     "expr": "ambient_weather_vapor_pressure_hpa",
     "legendFormat": "Vapor Pressure"
    },
    {
     "expr": "ambient_weather_vapor_pressure_deficit_hpa",
     "legendFormat": "VPD"
    }
   ]
  },
  {
   "title": "Evapotranspiration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ambient_weather_evapotranspiration_mm_day",
     "legendFormat": "Evapotranspiration"
    }
   ]
  },
  {
   "title": "Wind Run",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ambient_weather_wind_run_miles", "legendFormat": "Wind Run" }
   ]
  }
 ]
}